apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: demo
build:
  artifacts:
  - image: krunch-demo
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - kubectl/deployment.yaml
    - kubectl/ingress.yaml
    - kubectl/service.yaml
